### ISSUE TITLE
TIL dataset

### ISSUE THREAD

**Issue by icrto** [ivaxi0s/coop-cbm#1]
Hello,

Thank you for sharing the code to your work!
Regarding the TIL dataset, could you provide more information on how you obtained the data and how you processed it?

Thanks in advance.

**Comment by ivaxi0s** [comment]
Thank you for your interest in the work and our preprocessing of the TIL Dataset. The TIL TCGA dataset is opensource and available here - https://www.cancerimagingarchive.net/analysis-result/til-wsi-tcga/. As mentioned in the paper, we consider classification of TIL type, making 13 total classes. Specifically we used `TIL after thres v1 ` file The meta-data for the dataset is available here - https://cancerimagingarchive.net/datascope/TCGA_TilMap/. This can be downloaded as a csv file. To be compatible with the other CBM meta-data, we binarise these auxiliary information. I would be happy to send these pre-processed files over email. Feel free to reach out!

Hope this helps!

**Comment by icrto** [comment]
Thank you for the help!
I have emailed you as suggested :)
